### ISSUE TITLE
Linux crash

### ISSUE THREAD

**Issue by envis10n** [simulationcraft/simc#5699]
### Describe the bug
An error occurs while attempting to sim a specific character using the linux CLI executable.

### Expected behavior
Pull the character from armory, sim, and display results.

### To Reproduce
Run freshly compiled linux build, `simc armory=us,velen,nokhal`

### Additional information
```
SimulationCraft 902-01 for World of Warcraft 9.0.2.36949 Live (hotfix 2020-12-22/36949, git build shadowlands f8730e8993)

@@@@@simc: /home/envis10n/simc/engine/./lib/rapidjson/document.h:1059: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
[1]    2454 abort      simc armory=us,velen,nokhal
```

This same run works fine on the windows build, but crashes on every linux build I've tried.
```
Ubuntu 20.04 & Ubuntu Server 18.04.5
libcurl4-openssl-dev & libcurl4-gnutls-dev
```

**Comment by scamille** [comment]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff79eb859 in __GI_abort () at abort.c:79
#2  0x00007ffff79eb729 in __assert_fail_base (fmt=0x7ffff7b81588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555750b690 "false", file=0x55555750ac40 "/home/scamille/simc/engine/./lib/rapidjson/document.h", line=1059, function=<optimized out>)
    at assert.c:92
#3  0x00007ffff79fcf36 in __GI___assert_fail (assertion=0x55555750b690 "false", file=0x55555750ac40 "/home/scamille/simc/engine/./lib/rapidjson/document.h", line=1059, 
    function=0x55555750b568 "rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::Mem"...) at assert.c:101
#4  0x0000555556d729b1 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::operator[]<rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > (this=0x555559942ce8, name=...)
    at /home/scamille/simc/engine/./lib/rapidjson/document.h:1059
#5  0x0000555556d704b9 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::operator[]<char const> (this=0x555559942ce8, name=0x55555751ec4a "is_active")
    at /home/scamille/simc/engine/./lib/rapidjson/document.h:1039
#6  0x0000555556d705b3 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::operator[]<char const> (this=0x555559942ce8, name=0x55555751ec4a "is_active")
    at /home/scamille/simc/engine/./lib/rapidjson/document.h:1042
#7  0x0000555556e12724 in covenant::parse_blizzard_covenant_information (player=0x555559909350, covenant_data=...) at /home/scamille/simc/engine/player/covenant.cpp:711
#8  0x0000555556d65e29 in (anonymous namespace)::parse_soulbinds (p=0x555559909350, spec=..., covenant_info=..., caching=cache::CURRENT) at /home/scamille/simc/engine/interfaces/bcp_api.cpp:664
#9  0x0000555556d676c4 in (anonymous namespace)::parse_player (sim=0x7fffffffc750, player=..., caching=cache::CURRENT, allow_failures=false) at /home/scamille/simc/engine/interfaces/bcp_api.cpp:855
#10 0x0000555556d6a8de in bcp_api::download_player (sim=0x7fffffffc750, region="us", server="velen", name="nokhal", talents="active", caching=cache::CURRENT, allow_failures=false) at /home/scamille/simc/engine/interfaces/bcp_api.cpp:1193
#11 0x00005555570e7c1e in (anonymous namespace)::parse_armory (sim=0x7fffffffc750, name=..., value=...) at /home/scamille/simc/engine/sim/sc_sim.cpp:625
#12 0x0000555556bce0b4 in std::__invoke_impl<bool, bool (*&)(sim_t*, util::string_view, util::string_view), sim_t*, util::string_view, util::string_view> (
    __f=@0x5555596f49b8: 0x5555570e782d <(anonymous namespace)::parse_armory(sim_t*, util::string_view, util::string_view)>) at /usr/include/c++/10/bits/invoke.h:60
#13 0x0000555556bcc13d in std::__invoke_r<bool, bool (*&)(sim_t*, util::string_view, util::string_view), sim_t*, util::string_view, util::string_view> (
    __fn=@0x5555596f49b8: 0x5555570e782d <(anonymous namespace)::parse_armory(sim_t*, util::string_view, util::string_view)>) at /usr/include/c++/10/bits/invoke.h:141
#14 0x0000555556bc8e97 in std::_Function_handler<bool (sim_t*, util::string_view, util::string_view), bool (*)(sim_t*, util::string_view, util::string_view)>::_M_invoke(std::_Any_data const&, sim_t*&&, util::string_view&&, util::string_view&&) (__functor=..., 
    __args#0=@0x7fffffffc0d0: 0x7fffffffc750, __args#1=..., __args#2=...) at /usr/include/c++/10/bits/std_function.h:291
#15 0x000055555709c95a in std::function<bool (sim_t*, util::string_view, util::string_view)>::operator()(sim_t*, util::string_view, util::string_view) const (this=0x5555596f49b8, __args#0=0x7fffffffc750, __args#1=..., __args#2=...)
    at /usr/include/c++/10/bits/std_function.h:622
#16 0x0000555557095cd5 in (anonymous namespace)::opts_sim_func_t::do_parse (this=0x5555596f4990, sim=0x7fffffffc750, n=..., value=...) at /home/scamille/simc/engine/sim/sc_option.cpp:378
#17 0x0000555557096b3f in option_t::parse (this=0x5555596f4990, sim=0x7fffffffc750, name=..., value=...) at /home/scamille/simc/engine/sim/sc_option.cpp:571
#18 0x0000555557096d60 in opts::parse(sim_t*, util::span<std::unique_ptr<option_t, std::default_delete<option_t> > const, 18446744073709551615ul>, util::string_view, util::string_view, std::function<opts::parse_status (opts::parse_status, util::string_view, util::string_view)> const&) (sim=0x7fffffffc750, options=..., name=..., value=..., status_fn=...) at /home/scamille/simc/engine/sim/sc_option.cpp:593
#19 0x00005555570ff44a in sim_t::parse_option (this=0x7fffffffc750, name="armory", value="us,velen,nokhal") at /home/scamille/simc/engine/sim/sc_sim.cpp:3831
#20 0x00005555570ff63a in sim_t::setup (this=0x7fffffffc750, c=0x7fffffffc610) at /home/scamille/simc/engine/sim/sc_sim.cpp:3862
#21 0x000055555685f360 in sim_t::main (this=0x7fffffffc750, args=std::vector of length 1, capacity 1 = {...}) at /home/scamille/simc/engine/sc_main.cpp:282
#22 0x000055555685fc21 in main (argc=2, argv=0x7fffffffdbb8) at /home/scamille/simc/engine/sc_main.cpp:381
```

@navv1234 can you take a look at this please?

**Comment by envis10n** [comment]
Oh I should have added, I have only had this happen with this one character of mine. My other max level toon and a few of my guildies' characters don't have this issue.

**Comment by scamille** [comment]
Thanks for reporting the issue.

Since Blizzard just recently enabled souldbinds in their API, that is probably the reason why this occured just now.

If you build the default target with make on linux you will also get extra safety checks, which seem to have been triggered here.
(You can build a release version of SimC with ```make release``` which will run faster)

**Comment by navv1234** [comment]
Nah, I just overlooked the data model from their examples, missed the fact about "active" soulbind object member not being present always.

**Comment by envis10n** [comment]
> 
> 
> Thanks for reporting the issue.
> 
> Since Blizzard just recently enabled souldbinds in their API, that is probably the reason why this occured just now.
> 
> If you build the default target with make on linux you will also get extra safety checks, which seem to have been triggered here.
> (You can build a release version of SimC with `make release` which will run faster)

There is no target of "release" generated by cmake to then *make*.

**Comment by scamille** [comment]
yeah I was referring to the custom Makefile in /engine. With cmake that does not apply in the same way. I amnot sure what the default is for cmake - in any case don't build the debug version to run large simulations, which I assumed you did because of the assert.

**Comment by envis10n** [comment]
Ahh, I see. I built as debug because my current use case is inherently unstable and having any extra info is useful. Thanks
